reorder_impl_items = true
reorder_imports = true
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
wrap_comments = true
use_field_init_shorthand = true
format_strings = true
format_code_in_doc_comments = true
error_on_unformatted = true
condense_wildcard_suffixes = true
